### ISSUE TITLE
consider jcasbin-springboot-plugin refactoring 

### ISSUE THREAD

**Issue by jveverka** [jcasbin/jcasbin-springboot-plugin#1]
This jcasbin springboot example is quite simple and frankly it is not very well integrated with existing spring security subsystem. You may consider using example below [0] to refactor this demo. As you can see, jcabin is integrated with Spring's method security [1]. This enables Spring application programmers to obtain roles and user names in code and / or use method level RBAC anotations. 

[0] https://github.com/jveverka/java-11-examples/tree/master/spring/spring-jcasbin
[1] https://docs.spring.io/spring-security/site/docs/5.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#jc-method

**Comment by hsluoyz** [comment]
Hi @jveverka , do you have a standalone repo for your example? So I can just use your repo as a full example. This repo may be deprecated.

**Comment by hsluoyz** [comment]
Hi @jveverka , this plugin has been added to: https://github.com/casbin/casbin-website/commit/8f4e1e1940be5f3f0b8b908eed784913a65faa14
